# Load the Laravel image for PHP 8.2
image: lorisleiva/laravel-docker:8.2

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - export DB_HOST=mysql
            - composer install --no-interaction --no-progress --prefer-dist
            - php artisan test
          caches:
            - composer
          services:
            - mysql

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: 'testing'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'db'
        MYSQL_PASSWORD: 'db'
