# Load the Laravel image for PHP 8.2
image: lorisleiva/laravel-docker:8.2

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - cp .env.testing .env 
            #- export DB_HOST=127.0.0.1
            #- composer install --no-interaction --no-progress --prefer-dist
            #- ./vendor/bin/phpstan analyze --memory-limit=1G
            #- php artisan migrate
            #- php artisan db:seed
            #- php artisan test
          caches:
            - composer
          services:
            - mysql

      - step: 
          name: Deploy to api-staging.hvaindestad.nl
          deployment: staging
          trigger: manual
          script:
            # Backup the MySQL database
            - mysqldump -h $STAG_HVAINDESTAD_DB_HOST -u $STAG_HVAINDESTAD_DB_USER -p$STAG_HVAINDESTAD_DB_PASSWORD $STAG_HVAINDESTAD_DB_DATABASE > backup.sql
            - echo "Database backup created"
          artifacts:
            - db-dump.sql
      
definitions:
  services:
    mysql:
      image: mariadb:10.11
      environment:
        MARIADB_DATABASE: 'testing'
        MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
        MARIADB_USER: 'db'
        MARIADB_PASSWORD: 'db'
