# Load the Laravel image for PHP 8.2
image: lorisleiva/laravel-docker:8.2

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - composer phpstan
            - cp .env.testing .env 
            - export DB_HOST=127.0.0.1
            - composer install --no-interaction --no-progress --prefer-dist
            - php artisan migrate
            - php artisan db:seed
            - php artisan test
          caches:
            - composer
          services:
            - mysql

definitions:
  services:
    mysql:
      image: mariadb:10.11
      environment:
        MARIADB_DATABASE: 'testing'
        MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
        MARIADB_USER: 'db'
        MARIADB_PASSWORD: 'db'
