# Load the Laravel image for PHP 8.2
image: lorisleiva/laravel-docker:8.2

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - composer install --no-interaction --no-progress --prefer-dist
            - php artisan test
          caches:
            - composer
          services:
            - mysql

definitions:
  services:
    mysql:
      image: mariadb:10.11
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
        MARIADB_HOST: 127.0.0.1
        MARIADB_DATABASE: testing
        MARIADB_USER: db
        MARIADB_PASSWORD: db
